/* eslint-disable no-underscore-dangle */
export const _donates = [
  { item: 'Arroz' },
  { item: 'Feijão' },
  { item: 'Açúcar' },
  { item: 'Sal' },
  { item: 'Óleo' },
  { item: 'Café' },
  { item: 'Macarrão' },
  { item: 'Molho de tomate' },
  { item: 'Milho' },
  { item: 'Ervilha' },
  { item: 'Seleta' },
  { item: 'Farinha de trigo e de mandioca' },
  { item: 'Biscoito doce e salgado' },
  { item: 'Manteiga' },
  { item: 'Leite em pó' },
  { item: 'Sabonete' },
  { item: 'Creme dental' },
  { item: 'Desodorante' },
  { item: 'Shampoo' },
  { item: 'Condicionador' },
  { item: 'Papel higiênico' },
  { item: 'Sabão em pó' },
  { item: 'Amaciante' },
  { item: 'Água sanitária' },
  { item: 'Limpador multiuso' },
  { item: 'Detergente' },
  { item: 'Farinha de milho' },
  { item: 'Fubá' },
  { item: 'Lentilha' },
  { item: 'Feijão preto' },
  { item: 'Óleo' },
  { item: 'Azeite' },
  { item: 'Enlatados' },
  { item: 'Leite' },
  { item: 'Azeite' },
  { item: 'Kit higiene pessoal' },
];
