/* eslint-disable no-underscore-dangle */
export const _donates = [
  { label: 'Arroz', value: 'Arroz' },
  { label: 'Feijão', value: 'Feijão' },
  { label: 'Açúcar', value: 'Açúcar' },
  { label: 'Sal', value: 'Sal' },
  { label: 'Óleo', value: 'Óleo' },
  { label: 'Café', value: 'Café' },
  { label: 'Macarrão', value: 'Macarrão' },
  { label: 'Molho de tomate', value: 'Molho de tomate' },
  { label: 'Milho', value: 'Milho' },
  { label: 'Ervilha', value: 'Ervilha' },
  { label: 'Seleta', value: 'Seleta' },
  { label: 'Farinha de trigo e de mandioca', value: 'Farinha de trigo e de mandioca' },
  { label: 'Biscoito doce e salgado', value: 'Biscoito doce e salgado' },
  { label: 'Manteiga', value: 'Manteiga' },
  { label: 'Leite em pó', value: 'Leite em pó' },
  { label: 'Sabonete', value: 'Sabonete' },
  { label: 'Creme dental', value: 'Creme dental' },
  { label: 'Desodorante', value: 'Desodorante' },
  { label: 'Shampoo', value: 'Shampoo' },
  { label: 'Condicionador', value: 'Condicionador' },
  { label: 'Papel higiênico', value: 'Papel higiênico' },
  { label: 'Sabão em pó', value: 'Sabão em pó' },
  { label: 'Amaciante', value: 'Amaciante' },
  { label: 'Água sanitária', value: 'Água sanitária' },
  { label: 'Limpador multiuso', value: 'Limpador multiuso' },
  { label: 'Detergente', value: 'Detergente' },
  { label: 'Farinha de milho', value: 'Farinha de milho' },
  { label: 'Fubá', value: 'Fubá' },
  { label: 'Lentilha', value: 'Lentilha' },
  { label: 'Feijão preto', value: 'Feijão preto' },
  { label: 'Óleo', value: 'Óleo' },
  { label: 'Azeite', value: 'Azeite' },
  { label: 'Enlatados', value: 'Enlatados' },
  { label: 'Leite', value: 'Leite' },
  { label: 'Azeite', value: 'Azeite' },
  { label: 'Kit higiene pessoal', value: 'Kit higiene pessoal' },
  { label: 'Roupas e Calçados', value: 'Roupas e Calçados' },
  { label: 'Cesta básica P', value: 'Cesta básica P' },
  { label: 'Cesta básica M', value: 'Cesta básica M' },
  { label: 'Cesta básica G', value: 'Cesta básica G' }
];
